const data= [
{
    id:1,
    image:"https://images.pexels.com/photos/2017510/pexels-photo-2017510.jpeg?auto=compress&cs=tinysrgb&w=600",
    title:"George Sistonen",
    tag:["fitness","black"],
    description:"Person Doing Exhibition on Train Car",
    downloads:"1.4K",
    quality:"HD",
    likes:"51",
    source:"Pexels",
    our_choice:false
},
{
    id:1,
    image:"https://images.pexels.com/photos/4239547/pexels-photo-4239547.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"Alle Ksana",
    tag:["fitness","swimming","luxure","premium"],
    description:"Man Swimming in an Infinity Pool",
    downloads:"1.1K",
    quality:"HD",
    likes:"100",
    source:"Pexels",
    our_choice:true
},
{
    id:2,
    image:"https://images.pexels.com/photos/4634360/pexels-photo-4634360.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"Life Folks",
    tag:["nature"],
    description:"Brown Rock Formation on Beach",
    downloads:"3.2K",
    quality:"HD",
    likes:"100",
    source:"Pexels",
    our_choice:false
},
{
    id:3,
    image:"https://images.pexels.com/photos/5333096/pexels-photo-5333096.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"ALlan Franca",
    tag:["women","girl","aesthetic"],
    description:"Protesting young woman showing obscene gesture",
    downloads:"",
    quality:"HD",
    likes:"100",
    source:"Pexels",
    our_choice:true
},
{
    id:4,
    image:"https://images.pexels.com/photos/22807214/pexels-photo-22807214/free-photo-of-a-bull-in-a-field.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"Juan Luis Secø",
    tag:["nature","galaxy","sky","stars","night"],
    description:"A Bull in a Field",
    downloads:"2.9K",
    quality:"HD",
    likes:"100",
    source:"Pexels",
    our_choice:false
},
{
    id:5,
    image:"https://images.pexels.com/photos/12568979/pexels-photo-12568979.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"Dennis Ariel",
    tag:["astronomy","galaxy","stars"],
    description:"Photo of a Nebula and Stars",
    downloads:"4.1K",
    quality:"HD",
    likes:"100",
    source:"Pexels",
    our_choice:true
},

{
    id:6,
    image:"https://images.pexels.com/photos/23476465/pexels-photo-23476465/free-photo-of-car-with-its-doors-opened-against-night-sky-with-stars.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"Simranpreet Singh",
    tag:["nature","astronomy"],
    description:"Car With its Doors Opened Against Night Sky with Stars",
    downloads:"5.1K",
    quality:"HD",
    likes:"220",
    source:"Pexels",
    our_choice:false
},
{
    id:7,
    image:"https://images.pexels.com/photos/23669252/pexels-photo-23669252/free-photo-of-woman-in-headscarf-and-dress.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"Andrea Musto",
    tag:["women","aesthetic"],
    description:"Woman in Headscarf and Dress",
    downloads:"3.2K",
    quality:"HD",
    likes:"601",
    source:"Pexels",
    our_choice:false
},
{
    id:8,
    image:"https://images.pexels.com/photos/17091660/pexels-photo-17091660/free-photo-of-model-in-tied-orange-blouse-and-yellow-shorts.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"Vika Glitter",
    tag:["women","aesthetic","beauty"],
    description:"Model in Tied Orange Blouse and Yellow Shorts",
    downloads:"100K",
    quality:"HD",
    likes:"100",
    source:"Pexels",
    our_choice:true
},
{
    id:9,
    image:"https://images.pexels.com/photos/20393930/pexels-photo-20393930/free-photo-of-woman-in-bodysuit-fixing-hair-with-arm-raised.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"Vika Glitter",
    tag:["women","aesthetic","beauty"],
    description:"Woman in Bodysuit Fixing Hair with Arm Raised",
    downloads:"20K",
    quality:"HD",
    likes:"70",
    source:"Pexels",
    our_choice:true
},
{
    id:10,
    image:"https://images.pexels.com/photos/8728382/pexels-photo-8728382.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"Michelangelo Buonarroti",
    tag:["women","Ai","science"],
    description:"A Woman Using Virtual Goggles",
    downloads:"",
    quality:"HD",
    likes:"30",
    source:"Pexels",
    our_choice:false
},
{
    id:11,
    image:"https://images.pexels.com/photos/8728381/pexels-photo-8728381.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"Michelangelo Buonarroti",
    tag:["Ai","science"],
    description:"A man Using Virtual Goggles",
    downloads:"150K",
    quality:"HD",
    likes:"30",
    source:"Pexels",
    our_choice:false
},
{
    id:12,
    image:"https://images.pexels.com/photos/8728387/pexels-photo-8728387.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"Michelangelo Buonarroti",
    tag:["women","Ai","science"],
    description:"A Woman Using Virtual Goggles",
    downloads:"300K",
    quality:"HD",
    likes:"301",
    source:"Pexels",
    our_choice:false
},
{
    id:13,
    image:"https://images.pexels.com/photos/8098259/pexels-photo-8098259.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"RDNE Stock project",
    tag:["fitness","women","beauty","Ai"],
    description:"Woman dancing while wearing Virtual Reality Glasses",
    downloads:"1.1K",
    quality:"HD",
    likes:"20",
    source:"Pexels",
    our_choice:false
},
{
    id:15,
    image:"https://images.pexels.com/photos/8097328/pexels-photo-8097328.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"RDNE Stock project",
    tag:["fitness","women","beauty","Ai"],
    description:"Woman dancing while wearing Virtual Reality Glasses",
    downloads:"1.1K",
    quality:"HD",
    likes:"20",
    source:"Pexels",
    our_choice:true
},
{
    id:16,
    image:"https://images.pexels.com/photos/2417842/pexels-photo-2417842.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"Roberto Nickson",
    tag:["luxure","women"],
    description:"Woman Laying Down on Bed Inside Room",
    downloads:"102K",
    quality:"HD",
    likes:"99K",
    source:"Pexels",
    our_choice:false
},
{
    id:17,
    image:"https://images.pexels.com/photos/1545743/pexels-photo-1545743.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"may day.ua",
    tag:["luxure"],
    description:"Red Vehicle on the Road",
    downloads:"1K",
    quality:"HD",
    likes:"60",
    source:"Pexels",
    our_choice:false
},
{
    id:18,
    image:"https://images.pexels.com/photos/2417842/pexels-photo-2417842.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"may day.ua",
    tag:["luxure"],
    description:"Black Vehicle on the Road",
    downloads:"102K",
    quality:"HD",
    likes:"120K",
    source:"Pexels",
    our_choice:false
},
{
    id:19,
    image:"https://images.pexels.com/photos/1409957/pexels-photo-1409957.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title:"may day.ua",
    tag:["luxure","aesthetic"],
    description:"Cars Parked in parking",
    downloads:"12K",
    quality:"HD",
    likes:"10K",
    source:"Pexels",
    our_choice:false
},


]
export default data